sudo: required

services:
  - docker

script:
  - make test
  - make rmi
  - make build-prod

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: tinfa-travis-ci
  on:
    branch: production

notifications:
  email: false
  slack:
    if: branch = production
