sudo: required

language: node_js

node_js: lts/*

services:
  - docker

before_install:
  # update npm
  - npm i -g npm@7.8.0
  # update docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # update docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.4.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # install heroku
  - curl https://cli-assets.heroku.com/install.sh | sh

script:
  - docker build -t tinfa-travis-ci/node .
  - docker tag tinfa-travis-ci/node registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script: docker push atinfa-travis-ci/node;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: production

notifications:
  email: false
  slack:
    if: branch = production
