version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    networks:
      - financial-network

  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - financial-network
    depends_on:
      - mongo
    command: npm test

volumes:
  data:

networks:
  financial-network:
    driver: bridge
