version: '3'
services:
  mongo:
    restart: always
    container_name: mongo
    image: mongo

  node:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
