version: '3'
services:
  node:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - financial-network
    depends_on:
      - mongo

volumes:
  data:

networks:
  financial-network:
    driver: bridge
